/*
Auto-generated by: https://github.com/pmndrs/gltfjsx, then hand-edited for animation + swarm performance.
Model: "Drone" by Cafitz3D (https://sketchfab.com/Cafitz3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/) — credit required.
Source: https://sketchfab.com/3d-models/drone-2588b8a0917d474e97886763c98a65af
*/

import * as THREE from 'three'
import { useMemo, useRef } from 'react'
import { useFrame, type ThreeElements } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { mergeBufferGeometries } from 'three-stdlib'
import type { GLTF } from 'three-stdlib'
import { pointerWorld } from './pointerWorld'

const HOVER_RADIUS = 2.4

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_4: THREE.Mesh
    Object_40: THREE.Mesh
  }
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

const NOSE_MATRIX = new THREE.Matrix4().makeRotationY(Math.PI / 2)
const OFFSET_MATRIX = new THREE.Matrix4().compose(
  new THREE.Vector3(0.284, 0.705, 0),
  new THREE.Quaternion(),
  new THREE.Vector3(0.5, 0.5, 0.5),
)
const INNER_MATRIX = NOSE_MATRIX.clone().multiply(OFFSET_MATRIX)

function partMatrix(position?: [number, number, number], rotation?: [number, number, number], scale?: number | [number, number, number]) {
  const s = Array.isArray(scale) ? scale : [scale ?? 1, scale ?? 1, scale ?? 1]
  return new THREE.Matrix4().compose(
    new THREE.Vector3(...(position ?? [0, 0, 0])),
    new THREE.Quaternion().setFromEuler(new THREE.Euler(...(rotation ?? [0, 0, 0]))),
    new THREE.Vector3(...(s as [number, number, number])),
  )
}

function bakedGeometry(geometry: THREE.BufferGeometry, parentMatrix: THREE.Matrix4, local: THREE.Matrix4) {
  const g = geometry.clone()
  g.applyMatrix4(parentMatrix.clone().multiply(local))
  return g
}

// static (non-animated) parts merged into 3 draw calls, grouped by material — computed once and shared by every Drone instance
type StaticGeo = { body: THREE.BufferGeometry; nose: THREE.BufferGeometry; caps: THREE.BufferGeometry }
let staticGeoCache: StaticGeo | null = null

function getStaticGeometries(nodes: GLTFResult['nodes']): StaticGeo {
  if (staticGeoCache) return staticGeoCache

  const body = mergeBufferGeometries([
    bakedGeometry(nodes.Object_4.geometry, INNER_MATRIX, partMatrix()),
    bakedGeometry(nodes.Object_8.geometry, INNER_MATRIX, partMatrix([0.61, 0.373, -1.096], [0, -0.637, 0], 0.252)),
    bakedGeometry(nodes.Object_10.geometry, INNER_MATRIX, partMatrix([1.771, 0.644, -2.666], [0, -0.637, 0], 0.161)),
    bakedGeometry(nodes.Object_14.geometry, INNER_MATRIX, partMatrix([0.61, 0.373, 1.072], [Math.PI, -0.637, Math.PI], [-0.252, 0.252, 0.252])),
    bakedGeometry(nodes.Object_16.geometry, INNER_MATRIX, partMatrix([1.771, 0.644, 2.642], [Math.PI, -0.637, Math.PI], [-0.161, 0.161, 0.161])),
    bakedGeometry(nodes.Object_20.geometry, INNER_MATRIX, partMatrix([-1.329, 0.373, -1.096], [0, 0.637, 0], [-0.252, 0.252, 0.252])),
    bakedGeometry(nodes.Object_22.geometry, INNER_MATRIX, partMatrix([-2.49, 0.644, -2.666], [0, 0.637, 0], [-0.161, 0.161, 0.161])),
    bakedGeometry(nodes.Object_26.geometry, INNER_MATRIX, partMatrix([-1.329, 0.373, 1.072], [-Math.PI, 0.637, -Math.PI], 0.252)),
    bakedGeometry(nodes.Object_28.geometry, INNER_MATRIX, partMatrix([-2.49, 0.644, 2.642], [-Math.PI, 0.637, -Math.PI], 0.161)),
  ])!

  const nose = bakedGeometry(nodes.Object_6.geometry, INNER_MATRIX, partMatrix([1.621, 0.109, 0], undefined, [0.205, 0.205, 0.466]))

  const caps = mergeBufferGeometries([
    bakedGeometry(nodes.Object_12.geometry, INNER_MATRIX, partMatrix([1.771, 0.829, -2.666], [Math.PI, -1.053, Math.PI], 0.056)),
    bakedGeometry(nodes.Object_18.geometry, INNER_MATRIX, partMatrix([1.771, 0.829, 2.642], [0, -0.513, 0], [-0.056, 0.056, 0.056])),
    bakedGeometry(nodes.Object_24.geometry, INNER_MATRIX, partMatrix([-2.49, 0.829, -2.666], [Math.PI, 0.003, -Math.PI], [-0.056, 0.056, 0.056])),
    bakedGeometry(nodes.Object_30.geometry, INNER_MATRIX, partMatrix([-2.49, 0.829, 2.642], [0, 0.393, 0], 0.056)),
    bakedGeometry(nodes.Object_40.geometry, NOSE_MATRIX, partMatrix([-0.411, 1.205, -0.096], [0, -Math.PI / 2, 0], 0.217)),
  ])!

  staticGeoCache = { body, nose, caps }
  return staticGeoCache
}

// the 4 LED blades: [name, position, rotation, scale]
const BLADES = [
  { geo: 'Object_32', position: [1.872, 0.84, -2.608], rotation: [Math.PI, -1.053, Math.PI], scale: 0.139, light: [1.872, 0.6, -2.608] },
  { geo: 'Object_34', position: [1.828, 0.84, 2.54], rotation: [0, -0.513, 0], scale: [-0.139, 0.139, 0.139], light: [1.828, 0.6, 2.54] },
  { geo: 'Object_36', position: [-2.49, 0.84, -2.549], rotation: [Math.PI, 0.003, -Math.PI], scale: [-0.139, 0.139, 0.139], light: [-2.49, 0.6, -2.549] },
  { geo: 'Object_38', position: [-2.535, 0.84, 2.534], rotation: [0, 0.393, 0], scale: 0.139, light: [-2.535, 0.6, 2.534] },
] as const

export type DroneProps = ThreeElements['group'] & {
  /** the drone's current choreographed target — mutated in place, every frame, by a SwarmDirector */
  formationPosition: THREE.Vector3
  /** [x, z] amplitude of its small local wander on top of the formation position */
  wander?: [number, number]
  /** overall wander speed multiplier */
  speed?: number
  /** time offset so drones in a swarm don't wander in lockstep */
  phase?: number
  /** base hue (0-1) for this drone's LED color cycle */
  hue?: number
  spinSpeed?: number
  /** adds 4 real point lights for light-spill onto the body — fine for a hero shot, too expensive for a whole swarm */
  lit?: boolean
  /** when set, the show director drives the LED color (mutated in place each frame) instead of the built-in hue cycle */
  showColor?: THREE.Color
  /** multiplier on LED emissive intensity — crank it so a tiny far-away drone still reads as a light */
  glow?: number
}

export function Drone({
  formationPosition,
  wander = [0.5, 0.4],
  speed = 0.4,
  phase = 0,
  hue = 0,
  spinSpeed = 10,
  lit = false,
  showColor,
  glow = 1,
  ...groupProps
}: DroneProps) {
  const { nodes, materials } = useGLTF('/models/drone.glb') as unknown as GLTFResult
  const { body, nose, caps } = useMemo(() => getStaticGeometries(nodes), [nodes])

  const flightGroup = useRef<THREE.Group>(null!)
  const bladeRefs = useRef<THREE.Mesh[]>([])
  const lightRefs = useRef<THREE.PointLight[]>([])
  const lookTarget = useMemo(() => new THREE.Vector3(), [])
  const hoverBoost = useRef(0)

  const bladeMaterials = useMemo(
    () =>
      BLADES.map(
        () =>
          new THREE.MeshStandardMaterial({
            color: '#ffffff',
            emissive: '#35f2ff',
            emissiveIntensity: 2,
            toneMapped: false,
          }),
      ),
    [],
  )

  const addBlade = (mesh: THREE.Mesh | null) => {
    if (mesh && !bladeRefs.current.includes(mesh)) bladeRefs.current.push(mesh)
  }
  const addLight = (light: THREE.PointLight | null) => {
    if (light && !lightRefs.current.includes(light)) lightRefs.current.push(light)
  }

  useFrame((state, delta) => {
    const t = state.clock.elapsedTime * speed + phase

    // glow boost from proximity to the cursor — every drone within HOVER_RADIUS reacts, not just one under the pointer
    const dx = flightGroup.current.position.x - pointerWorld.x
    const dy = flightGroup.current.position.y - pointerWorld.y
    const dist = Math.hypot(dx, dy)
    const near = Math.max(0, 1 - dist / HOVER_RADIUS)
    const targetBoost = near * near * (3 - 2 * near) // smoothstep
    hoverBoost.current = THREE.MathUtils.damp(hoverBoost.current, targetBoost, 6, delta)
    const boost = hoverBoost.current

    for (const mesh of bladeRefs.current) mesh.rotation.y += delta * spinSpeed * (1 + boost)

    bladeMaterials.forEach((mat, i) => {
      const pulse = (1.8 + Math.sin(state.clock.elapsedTime * 6 + i + phase) * 0.8 + boost * 4) * glow
      if (showColor) {
        mat.color.copy(showColor)
        mat.emissive.copy(showColor)
      } else {
        const h = (hue + t * (0.25 + boost * 0.6) + i * 0.25) % 1
        mat.color.setHSL(h, 1, 0.5 + boost * 0.15)
        mat.emissive.setHSL(h, 1, 0.5 + boost * 0.15)
      }
      mat.emissiveIntensity = pulse

      const light = lightRefs.current[i]
      if (light) {
        light.color.copy(mat.emissive)
        light.intensity = pulse
      }
    })

    const x = formationPosition.x + Math.sin(t) * wander[0]
    const z = formationPosition.z + Math.sin(t * 2) * wander[1]
    const y = formationPosition.y + Math.sin(t * 1.5) * wander[1] * 0.6
    flightGroup.current.position.set(x, y, z)

    const t2 = t + 0.05
    lookTarget.set(formationPosition.x + Math.sin(t2) * wander[0], y, formationPosition.z + Math.sin(t2 * 2) * wander[1])
    flightGroup.current.lookAt(lookTarget)
    flightGroup.current.rotation.z += Math.sin(t * 2) * 0.15
  })

  return (
    <group ref={flightGroup} {...groupProps} dispose={null}>
      <mesh geometry={body} material={materials.Material} />
      <mesh geometry={nose} material={materials['Material.003']} />
      <mesh geometry={caps} material={materials['Material.001']} />

      <group rotation={[0, Math.PI / 2, 0]}>
        <group position={[0.284, 0.705, 0]} scale={0.5}>
          {BLADES.map((blade, i) => (
            <group key={blade.geo}>
              <mesh
                ref={addBlade}
                geometry={nodes[blade.geo].geometry}
                material={bladeMaterials[i]}
                position={blade.position as unknown as [number, number, number]}
                rotation={blade.rotation as unknown as [number, number, number]}
                scale={blade.scale as unknown as number | [number, number, number]}
              />
              {lit && <pointLight ref={addLight} position={blade.light as unknown as [number, number, number]} color="#35f2ff" intensity={4} distance={5} />}
            </group>
          ))}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/drone.glb')
